### ISSUE TITLE
Default icon is not working correctly

### ISSUE THREAD

**Issue by sethen** [nvim-tree/nvim-web-devicons#449]
I've set a default icon but for whatever reason it's not being picked up by certain files.  For instance:

![Screenshot from 2024-04-22 19-03-18](https://github.com/nvim-tree/nvim-web-devicons/assets/1493530/dbb0c6c8-65cf-4b96-ad2f-59c098bad8db)

However, the setup shows the icon perfectly fine:

![Screenshot from 2024-04-22 19-04-14](https://github.com/nvim-tree/nvim-web-devicons/assets/1493530/9c678960-ab0e-4b8c-a46c-4b9599230c4f)

As you can see the editor renders the page icon just fine but it is not applying it to all icons as a default.

**Comment by sethen** [comment]
I solved _some_ of my issue.  Part of it was I had to set some things for the file tree explorer itself.  However, the default icon isn't working for everything.

**Comment by alex-courtis** [comment]
What is the plugin that displays the icons?

**Comment by sethen** [comment]
> To confirm: does the default default icon show when you remove `set_default_icon` ?

Not sure what you mean... if I delete the `set_delete_icon` function does the default icon show??

**Comment by sethen** [comment]
Here is also another thing I am seeing -- I would assume the default icon would take over here when the `TelescopePrompt` comes up but it doesn't... However, it does when the `help` buffer is open.  Check the status bar on the bottom right.

No default icon:
![Screenshot from 2024-04-24 19-39-35](https://github.com/nvim-tree/nvim-web-devicons/assets/1493530/ad2df4d1-df42-4b5f-9def-11c09e1c4e1a)

Default icon:
![Screenshot from 2024-04-24 19-42-28](https://github.com/nvim-tree/nvim-web-devicons/assets/1493530/22590b44-1048-4e93-8946-609731345ad1)

**Comment by alex-courtis** [comment]
Experimenting with your setup:

```lua
require("nvim-web-devicons").set_default_icon('D', '#6d8086', 65)
print(vim.inspect(require("nvim-web-devicons").get_default_icon()))
```
```lua
{
  color = "#6d8086",
  cterm_color = 65,
  icon = "D",
  name = "Default"
}
```

```lua
require("nvim-web-devicons").set_default_icon('X')
print(vim.inspect(require("nvim-web-devicons").get_default_icon()))
```
```lua
{
  icon = "X",
  name = "Default"
}
```

That is working as intended, presuming that `icon` in your screenshot is `require("nvim-web-devicons")`

**Comment by alex-courtis** [comment]
> > To confirm: does the default default icon show when you remove `set_default_icon` ?
> 
> Not sure what you mean... if I delete the `set_delete_icon` function does the default icon show??

Yes.

However... that's not to say that nvim-tree, telescope or lualine will actually use it, they may use their own.

Experimenting with nvim-tree and `:NvimWebDeviconsHiTest` shows that the default icon is not shown or used. Investigating...

**Comment by alex-courtis** [comment]
`:NvimWebDeviconsHiTest` not showing the default is unrelated. Fixed at #451 

nvim-tree is not showing the default icon, contradicting help: 
```help
            *nvim-tree.renderer.icons.web_devicons.file.enable*
            Show icons on files.
            Overrides |nvim-tree.renderer.icons.glyphs.default|
              Type: `boolean`, Default: `true`

        *nvim-tree.renderer.icons.glyphs.default*
        Glyph for files.
        Overridden by |nvim-tree.renderer.icons.web_devicons| if available.
          Type: `string`, Default: `""`
```

**Comment by alex-courtis** [comment]
RE lualine:  it does not show default icons. I'll leave telescope to you...

**Comment by sethen** [comment]
> RE lualine: it does not show default icons. I'll leave telescope to you...
> 
> Does resolution of this issue resolve your concerns? [nvim-tree/nvim-tree.lua#2758 (comment)](https://github.com/nvim-tree/nvim-tree.lua/issues/2758#issuecomment-2081313671)

I left a comment over there.  Happy to test, just unsure how.

**Comment by alex-courtis** [comment]
Fixed via #2759

**Comment by sethen** [comment]
@alex-courtis Still not seeing the default icon taking effect even after updating.

**Comment by alex-courtis** [comment]
> @alex-courtis Still not seeing the default icon taking effect even after updating nvim-tree.

That's no good; we'll get to the bottom of this. I reckon it's nvim-tree.

Please raise an nvim-tree [bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) with your nvim-tree and nvim-webdevicons minimal configuration so that we may reproduce and fix.
